# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a slim Python image as the base
FROM python:3.12-slim AS base

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install UV and the project's dependencies
RUN pip install uv \
    && uv pip install -e ".[dev]"

# Create the configuration directory and add default config
RUN mkdir -p /app/proxmox-config \
    && cp /app/config/config.example.json /app/proxmox-config/config.json

# Set environment variables
ENV PROXMOX_CONFIG_PATH=/app/proxmox-config/config.json

# Expose the port that the MCP server will run on
EXPOSE 8000

# Run the server
CMD ["python", "-m", "proxmox_mcp.server"]
